### PR TITLE
Added help command

### PR DESCRIPTION
**Pull request by MAPReiff**
Added a help command and updated the README to reflect the change

### CODE REVIEW

**Comment by paulguy** [comment]
Thanks for the commit.  I just would like the help string split across multiple lines so it's not just 1 long run-on line. You can split a string in C by putting each line of the string in quotes like:
```
char *foo = "this is a line\n"
"this is another"
"line.\n";
```

**Comment by MAPReiff** [comment]
Fixed it

**Comment by paulguy** [comment]
The spot to print help text is only reached if opening a device has succeeded, so the help text won't print in that case, and it also requires opening the device just to print the text.  I'm sure this could be rearranged to make it work but I don't really have that much interest in doing so.

**Comment by paulguy** [comment]
Thanks for the fixes.  it appears to work now.  Formatting is a bit sloppy but it's mostly whatever but something to keep in mind to keep things lined up the same way as the original had it (or whatever other formatting the code base being contributed to seems to have or if they have any specific guidelines written out).

**Pull request merged**
